const services = [
  { id: 'documents', icon: '▤', name: 'Document services', short: 'Apply for or renew identity documents and certificates.', duration: 'About 20 minutes', description: 'Get help with common identity documents and official certificates at your local service centre.', requirements: ['A valid photo ID, if available', 'Completed application form', 'Supporting documents for your request'], slots: ['9:00 AM', '10:30 AM', '11:15 AM', '1:00 PM', '2:30 PM', '3:15 PM'] },
  { id: 'permits', icon: '⌂', name: 'Permits & licences', short: 'Get guidance on local permits, licences, and applications.', duration: 'About 30 minutes', description: 'Speak with a service officer about a local permit or licence application.', requirements: ['Photo ID', 'Application reference, if you have one', 'Relevant plans or supporting paperwork'], slots: ['9:30 AM', '10:00 AM', '11:30 AM', '1:30 PM', '2:00 PM', '3:30 PM'] },
  { id: 'tax', icon: '₹', name: 'Tax assistance', short: 'Get help finding the right forms and public tax services.', duration: 'About 25 minutes', description: 'A staff member can help you find the right public tax service and understand the next steps.', requirements: ['Photo ID', 'Any letters or forms related to your question', 'Your tax reference, if applicable'], slots: ['9:00 AM', '10:15 AM', '11:00 AM', '12:30 PM', '2:00 PM', '3:00 PM'] },
  { id: 'housing', icon: '⌂', name: 'Housing support', short: 'Talk through housing support and community resources.', duration: 'About 30 minutes', description: 'Get connected with local housing support and learn about available community resources.', requirements: ['Photo ID, if available', 'Proof of address, if available', 'Any relevant case or application number'], slots: ['9:15 AM', '10:45 AM', '11:30 AM', '1:00 PM', '2:15 PM', '3:45 PM'] },
  { id: 'business', icon: '▣', name: 'Small business help', short: 'Find guidance for registrations, forms, and local resources.', duration: 'About 30 minutes', description: 'Get pointed to the correct public resources for starting or managing a small business.', requirements: ['Photo ID', 'Business registration details, if available', 'A short note about what you need help with'], slots: ['9:30 AM', '10:30 AM', '12:00 PM', '1:15 PM', '2:45 PM', '3:30 PM'] },
  { id: 'community', icon: '♡', name: 'Community services', short: 'Find local support programmes and community services.', duration: 'About 20 minutes', description: 'Explore local community services and get help finding a programme that suits your needs.', requirements: ['Photo ID, if available', 'A short note about the support you are looking for'], slots: ['9:00 AM', '10:00 AM', '11:15 AM', '1:30 PM', '2:15 PM', '3:00 PM'] }
];
const dayOffset = (n) => { const d = new Date(); d.setDate(d.getDate() + n); return d; };
const dayLabel = (d) => new Intl.DateTimeFormat('en-IN', { weekday: 'short', day: 'numeric', month: 'short' }).format(d);
let selectedService = null; let selectedDate = null; let selectedSlot = null; let rescheduleId = null;
const byId = (id) => document.getElementById(id);
const loadBookings = () => { try { return JSON.parse(localStorage.getItem('civicease-bookings') || '[]'); } catch { return []; } };
const saveBookings = (items) => { localStorage.setItem('civicease-bookings', JSON.stringify(items)); updateCount(); };
function updateCount() { byId('bookingCount').textContent = loadBookings().length; }
function renderServices(filter = '') { const grid = byId('serviceGrid'); grid.innerHTML = ''; const list = services.filter(s => `${s.name} ${s.short}`.toLowerCase().includes(filter.toLowerCase())); byId('noResults').hidden = list.length > 0; list.forEach(s => { const card = document.createElement('article'); card.className = 'service-card'; card.innerHTML = `<div class="service-icon">${s.icon}</div><h3>${s.name}</h3><p>${s.short}</p><div class="service-meta"><span class="duration">◷ &nbsp;${s.duration}</span><button class="card-link" data-service="${s.id}">View & book <span>→</span></button></div>`; grid.append(card); }); }
function showModal(content) { byId('modalContent').innerHTML = content; byId('modalBackdrop').hidden = false; document.body.classList.add('body-lock'); }
function closeModal() { byId('modalBackdrop').hidden = true; document.body.classList.remove('body-lock'); selectedService = null; selectedDate = null; selectedSlot = null; rescheduleId = null; }
function openService(id) { selectedService = services.find(s => s.id === id); if (!selectedService) return; selectedDate = dayOffset(1); const s = selectedService; showModal(`<div class="eyebrow">PUBLIC SERVICE</div><h2 id="modalTitle">${s.name}</h2><p>${s.description}</p><div class="requirements"><h3>What to bring</h3><ul>${s.requirements.map(x => `<li>${x}</li>`).join('')}</ul></div><label class="field-label" for="dateSelect">Choose a day</label><select id="dateSelect" class="form-grid" style="width:100%;border:1px solid #dfe6df;border-radius:6px;padding:10px;font:11px var(--sans)">${[1,2,3,4,5].map(n=>`<option value="${dayOffset(n).toISOString()}" ${n===1?'selected':''}>${dayLabel(dayOffset(n))}</option>`).join('')}</select><label class="field-label">Available times</label><div class="slot-grid">${s.slots.map((t,i)=>`<button class="slot" data-slot="${t}" ${i===4?'disabled':''}>${t}${i===4?' · Full':''}</button>`).join('')}</div><div id="bookingForm"></div>`); byId('modalTitle').textContent = s.name; }
function showBookingForm() { if (!selectedSlot) return; byId('bookingForm').innerHTML = `<form id="bookForm"><div class="form-grid"><label>Your name<input name="name" required placeholder="Full name" maxlength="60"></label><label>Email address<input name="email" type="email" required placeholder="you@example.com"></label></div><button class="primary-button modal-action">${rescheduleId ? 'Confirm new time' : 'Confirm appointment'} <span>→</span></button></form>`; byId('bookingForm').scrollIntoView({behavior:'smooth',block:'nearest'}); }
function openBookings() { const items = loadBookings(); showModal(`<div class="eyebrow">YOUR VISITS</div><h2 id="modalTitle">My appointments</h2><p>Bookings are saved in this browser for this project demo.</p><div id="bookingList"></div>`); const list = byId('bookingList'); if (!items.length) { list.innerHTML = '<div class="empty-bookings">You have no appointments yet.<br>Choose a service to book your first visit.</div>'; return; } list.innerHTML = items.map(b=>`<article class="booking-item"><h3>${escapeText(b.serviceName)}</h3><p>${escapeText(b.dateLabel)} · ${escapeText(b.time)}</p><p>${escapeText(b.name)} · ${escapeText(b.email)}</p><span class="booking-id">Reference: ${escapeText(b.ref)}</span><div class="booking-actions"><button class="text-action" data-reschedule="${b.id}">Reschedule</button><button class="text-action" data-cancel="${b.id}">Cancel</button></div></article>`).join(''); }
function escapeText(s) { const d=document.createElement('div'); d.textContent=String(s); return d.innerHTML; }
function startReschedule(id) { const b=loadBookings().find(x=>x.id===id); if (!b) return; rescheduleId=id; openService(b.serviceId); const title=byId('modalTitle'); if(title) title.textContent=`Reschedule ${b.serviceName}`; }
function chatAnswer(text) { const q=text.toLowerCase(); if (/bring|document|require|need/.test(q)) return 'What to bring depends on the service. Choose a service card to see its sample checklist. If you are unsure, bring a photo ID and any related forms or reference numbers you have.'; if (/reschedul|change.*time|change.*booking/.test(q)) return 'Open “My appointments” at the top of the page and choose Reschedule on your booking. Pick a new day and time, then confirm.'; if (/cancel/.test(q)) return 'Open “My appointments” and select Cancel beside the appointment you want to remove.'; if (/book|appointment|slot|time/.test(q)) return 'Choose a service, select an available day and time, then enter your name and email to confirm. This demo saves the booking in your browser.'; if (/hours|open|location|where/.test(q)) return 'For this prototype, visits are shown at the Central Service Centre and sample times run from 9 AM to 4 PM. Check with your local office for real opening hours and locations.'; const found=services.find(s=>q.includes(s.name.toLowerCase().split(' ')[0])); if(found) return `${found.name}: ${found.short} ${found.requirements.length ? 'Open the service card to see its sample checklist and available times.' : ''}`; return 'I can help with the sample service requirements, booking, rescheduling, and cancellations. Try asking “What should I bring?”'; }
function addMessage(text, who) { const el=document.createElement('div'); el.className=`message ${who}`; el.textContent=text; byId('chatMessages').append(el); byId('chatMessages').scrollTop=byId('chatMessages').scrollHeight; }
byId('serviceGrid').addEventListener('click',e=>{const b=e.target.closest('[data-service]');if(b)openService(b.dataset.service);});
byId('serviceSearch').addEventListener('input',e=>renderServices(e.target.value));
byId('openBookings').addEventListener('click',openBookings); byId('closeModal').addEventListener('click',closeModal); byId('modalBackdrop').addEventListener('click',e=>{if(e.target===byId('modalBackdrop'))closeModal();});
document.addEventListener('keydown',e=>{if(e.key==='Escape'){closeModal();closeAssistant();}});
byId('modalContent').addEventListener('change',e=>{if(e.target.id==='dateSelect')selectedDate=new Date(e.target.value);});
byId('modalContent').addEventListener('click',e=>{const slot=e.target.closest('[data-slot]');if(slot){selectedSlot=slot.dataset.slot;byId('modalContent').querySelectorAll('.slot').forEach(x=>x.classList.toggle('selected',x===slot));showBookingForm();return;}const cancel=e.target.closest('[data-cancel]');if(cancel){const b=loadBookings().find(x=>x.id===cancel.dataset.cancel);if(!b)return;if(confirm(`Cancel your ${b.serviceName} appointment?`)){saveBookings(loadBookings().filter(x=>x.id!==b.id));openBookings();}return;}const res=e.target.closest('[data-reschedule]');if(res)startReschedule(res.dataset.reschedule);});
byId('modalContent').addEventListener('submit',e=>{if(e.target.id!=='bookForm')return;e.preventDefault();const data=new FormData(e.target);const name=String(data.get('name')).trim(),email=String(data.get('email')).trim();if(!name||!email||!selectedSlot)return;let items=loadBookings();let ref;if(rescheduleId){const existing=items.find(b=>b.id===rescheduleId);ref=existing?.ref||`CE-${Math.random().toString(36).slice(2,8).toUpperCase()}`;items=items.map(b=>b.id===rescheduleId?{...b,date:selectedDate.toISOString(),dateLabel:dayLabel(selectedDate),time:selectedSlot}:b);}else{ref=`CE-${Math.random().toString(36).slice(2,8).toUpperCase()}`;items.push({id:crypto.randomUUID?crypto.randomUUID():String(Date.now()),serviceId:selectedService.id,serviceName:selectedService.name,date:selectedDate.toISOString(),dateLabel:dayLabel(selectedDate),time:selectedSlot,name,email,ref});}saveBookings(items);showModal(`<div class="eyebrow">${rescheduleId?'UPDATED':'YOU’RE BOOKED'}</div><h2 id="modalTitle">${rescheduleId?'Appointment rescheduled':'Appointment confirmed'}</h2><p>${rescheduleId?'Your new appointment time is confirmed.':'Your appointment has been added to this browser.'}</p><div class="notice"><b>${escapeText(selectedService.name)}</b><br>${escapeText(dayLabel(selectedDate))} · ${escapeText(selectedSlot)}<br>Reference: ${ref}<br><br>Bring the documents listed for your service. This prototype does not send a real email confirmation.</div><button class="primary-button modal-action" id="doneButton">Done</button>`);byId('doneButton').addEventListener('click',closeModal);});
const panel=byId('assistantPanel');function closeAssistant(){panel.classList.remove('open');panel.setAttribute('aria-hidden','true');}function openAssistant(){panel.classList.add('open');panel.setAttribute('aria-hidden','false');byId('chatInput').focus();}byId('assistantFab').addEventListener('click',openAssistant);byId('openAssistant').addEventListener('click',openAssistant);byId('closeAssistant').addEventListener('click',closeAssistant);
byId('chatForm').addEventListener('submit',e=>{e.preventDefault();const input=byId('chatInput');const text=input.value.trim();if(!text)return;addMessage(text,'user');input.value='';setTimeout(()=>addMessage(chatAnswer(text),'bot'),250);});
byId('chatMessages').addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;byId('chatInput').value=b.textContent;byId('chatForm').requestSubmit();});
renderServices();updateCount();
